#### Get Valid Account ID
GET http://localhost:8000/api/v1/account/1 HTTP/1.1
content-type: application/json
Authorization: Token f6f9922cc3503642ae89e0cd80d6fbc635cb50c4

#### Get Invalid Account ID
GET http://localhost:8000/api/v1/account/12 HTTP/1.1
content-type: application/json
Authorization: Token f6f9922cc3503642ae89e0cd80d6fbc635cb50c4

#### MAKE VALID EXT TRANSACTION
POST http://localhost:8000/api/v1/transaction HTTP/1.1
content-type: application/json
Authorization: Token f6f9922cc3503642ae89e0cd80d6fbc635cb50c4

{
    "recipient_account": "1",
    "creditor_account": "3",
    "recipient_text": "Some explanation",
    "amount": "100.0",
    "ref" : 1234
}

### Get API token
POST http://localhost:8000/api/v1/rest-auth/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=Manager
&password=bankia12