# Generated by Django 3.2.7 on 2021-10-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210927_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rank',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='bank.rank'),
        ),
    ]
