# Generated by Django 3.2.7 on 2022-06-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_customer_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mfa_token',
            field=models.SmallIntegerField(db_index=True, default=None),
        ),
        migrations.CreateModel(
            name='External_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_transaction', models.IntegerField(db_index=True)),
                ('our_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.ledger')),
            ],
        ),
    ]
