# Generated by Django 3.2.7 on 2022-06-04 15:44

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_ledger',
            name='status',
            field=models.CharField(choices=[(bank.models.ExternalTransactionStatus['C'], 'Created'), (bank.models.ExternalTransactionStatus['V'], 'Validated')], default=bank.models.ExternalTransactionStatus['C'], max_length=2),
        ),
    ]
